### ISSUE TITLE
ArcGis API token with Nextjs

### ISSUE THREAD

**Issue by enkicoma** [benelan/arcgis-esm-samples#8]
Hi,

thx for the template of ArcGis and Next.js 

can you help me please to understand what environment variable or approach should i take, when using the API key?
`esriConfig.apiKey = "YOUR_API_KEY";`
https://developers.arcgis.com/javascript/latest/add-a-feature-layer/

I know that next js has configured `.env.local`

but I tried to call the API key through the function getStaticProps and didn't work...
https://nextjs.org/docs/basic-features/environment-variables
<img width="716" alt="Screenshot 2022-12-23 at 11 40 52" src="https://user-images.githubusercontent.com/29044574/209330317-9fc4be0d-cc40-4f5b-af91-06aeff9e76af.png">

but if I do NEXT_PUBLIC it works, mean that the API key can't be used on the server side and requires it at the browser client side? Or maybe I don't know how to use static props... (an example will be useful in your repo)

Please help ^_^ want to make sure not exposing my key public 
ArcGIS Maps SDK for JavaScript 4.25
[Add a feature layer | Overview | ArcGIS Maps SDK for JavaScript 4.2...](https://developers.arcgis.com/javascript/latest/add-a-feature-layer/)
Documentation site for ArcGIS Maps SDK for JavaScript on ArcGIS Developers.

**Comment by benelan** [comment]
Hi, I'm glad you found the sample helpful! I pushed a [new branch](https://github.com/benelan/arcgis-esm-samples/tree/benelan/api-key-nextjs) that demonstrates passing the API KEY to the map component via `getStaticProps`, since that's what you requested.

However, if you're concerned about the security I suggest contacting Esri Support Services for advice on managing your keys. My time is focused on Calcite Components these days so I'm not knowledgable on that subject.

Hope the example helps!
